services:
  lifechecker:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "namecheap_lifechecker"
    volumes:
      - "/var/lib/lifechecker:/var/lib/lifechecker:ro"
    environment:
      NAMECHEAP_LIFECHECKS_ENVIRONMENT: "${NAMECHEAP_LIFECHECKS_ENVIRONMENT}"
      NAMECHEAP_LIFECHECKS_GATEWAY_IP: "${NAMECHEAP_LIFECHECKS_GATEWAY_IP}"
      NAMECHEAP_LIFECHECKS_CSV_PATH: "${NAMECHEAP_LIFECHECKS_CSV_PATH}"
      NAMECHEAP_LIFECHECKS_TELEGRAM_BOT_TOKEN: "${NAMECHEAP_LIFECHECKS_TELEGRAM_BOT_TOKEN}"
      NAMECHEAP_LIFECHECKS_TELEGRAM_CHAT_ID: "${NAMECHEAP_LIFECHECKS_TELEGRAM_CHAT_ID}"
      NAMECHEAP_LIFECHECKS_TELEGRAM_MESSAGE_THREAD_ID: "${NAMECHEAP_LIFECHECKS_TELEGRAM_MESSAGE_THREAD_ID}"