[project]
name = "namecheap-lifechecks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp[speedups]>=3.12.15",
    "mypy>=1.17.1",
    "ruff>=0.12.8",
]
